/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompanyCard: typeof import('./src/components/CompanyCard/CompanyCard.vue')['default']
    copy: typeof import('./src/components/Header/HeaderBase copy.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    FooterBase: typeof import('./src/components/Footer/FooterBase.vue')['default']
    FooterHelp: typeof import('./src/components/Footer/FooterHelp.vue')['default']
    HeaderBase: typeof import('./src/components/Header/HeaderBase.vue')['default']
    HeaderHelp: typeof import('./src/components/Header/HeaderHelp.vue')['default']
    HeaderShop: typeof import('./src/components/Header/HeaderShop.vue')['default']
    HeaderUser: typeof import('./src/components/Header/HeaderUser.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default']
    IEpChatDotSquare: typeof import('~icons/ep/chat-dot-square')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpPaperclip: typeof import('~icons/ep/paperclip')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IEpSort: typeof import('~icons/ep/sort')['default']
    MenuCate: typeof import('./src/components/MenuCate/MenuCate.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/ProductCard.vue')['default']
    ProductCardSimple: typeof import('./src/components/ProductCard/ProductCardSimple.vue')['default']
    ProductFocusing: typeof import('./src/components/ProductFocusing/ProductFocusing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAddress: typeof import('./src/components/Table/TableAddress.vue')['default']
    TableOrder: typeof import('./src/components/Table/TableOrder.vue')['default']
    TableOrderBank: typeof import('./src/components/Table/TableOrderBank.vue')['default']
    TableProduct: typeof import('./src/components/Table/TableProduct.vue')['default']
    TableQuery: typeof import('./src/components/Table/TableQuery.vue')['default']
    TableQueryProduct: typeof import('./src/components/Table/TableQueryProduct.vue')['default']
    TableSku: typeof import('./src/components/Table/TableSku.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
