/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FooterBase: typeof import('./src/components/FooterBase/FooterBase.vue')['default']
    HeaderBase: typeof import('./src/components/HeaderBase/HeaderBase.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpClock: typeof import('~icons/ep/clock')['default']
    IEpPaperclip: typeof import('~icons/ep/paperclip')['default']
    IEpPhone: typeof import('~icons/ep/phone')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
